[build-system]
requires = ["scikit-build",   "pybind11", "cmake>=3.11", "ninja", "numpy"]

[project]
name = "pdal"
description = "oint cloud data processing"
version = "3.2.3"

dependencies = ["numpy"]
